# Generated by Django 5.1.7 on 2025-05-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(default='No bio yet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='No bio yet', upload_to='Author/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('writer', 'Writer')], default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
    ]
